# Generated by Django 2.0.5 on 2019-01-06 11:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=39)),
                ('last_name', models.CharField(max_length=39)),
            ],
        ),
        migrations.CreateModel(
            name='Loan_paid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField()),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_amount', to='loan.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amt', models.IntegerField()),
                ('interest_rate', models.IntegerField()),
                ('loan_date', models.DateField(default=datetime.date.today)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_name', to='loan.Client')),
            ],
        ),
    ]
