# Generated by Django 2.0.5 on 2019-01-09 07:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0002_auto_20190107_1047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan_paid',
            new_name='LoanPaid',
        ),
        migrations.RenameModel(
            old_name='Loan_taken',
            new_name='LoanTaken',
        ),
    ]
